/* Builds assets/data/site-stats.json: every figure the hand-built pages quote, as display text.
   Sources: assets/data/gcc-atlas.json (written by buildatlas.js from public.atlas_stats()) and
   public.site_stats() (setup models, maturity by founding year). Nothing here is typed by hand.
   sync.js then stamps these values into every page, meta tag, JSON-LD block and llms.txt.
   Percentages follow buildpages.js: one decimal, against the full scope total. */
const fs = require('fs'), path = require('path');
const S = path.join(__dirname, '..').replace(/\\/g, '/') + '/';
const A = JSON.parse(fs.readFileSync(S + 'assets/data/gcc-atlas.json', 'utf8'));
const SUPA = 'https://fufnvnvufmrhrzhcoeil.supabase.co';
const KEY = (fs.readFileSync(S + 'console.html', 'utf8').match(/sb_publishable_[A-Za-z0-9_-]{10,}|eyJhbGciOi[A-Za-z0-9_.-]{20,}/) || [])[0];

const fmt = n => Number(n).toLocaleString('en-US');
const pc = (n, d) => Math.round(n / d * 1000) / 10;
const pct0 = (n, d) => Math.round(n / d * 100) + '%';
const floor100 = n => fmt(Math.floor(n / 100) * 100) + '+';
const val = (dim, scope, key) => { const r = (A.dims[dim][scope] || []).find(x => x[0] === key); return r ? r[1] : 0; };
const known = (dim, scope) => A.scope_totals[scope] - val(dim, scope, 'Not disclosed');
const LONG = iso => new Date(iso + 'T12:00:00Z').toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });

async function siteStats() {
  if (!KEY) throw new Error('No publishable key found in console.html');
  const r = await fetch(SUPA + '/rest/v1/rpc/site_stats', { method: 'POST', headers: { apikey: KEY, Authorization: 'Bearer ' + KEY, 'Content-Type': 'application/json' }, body: '{}' });
  if (!r.ok) throw new Error('site_stats() returned ' + r.status);
  return r.json();
}

(async () => {
  const X = await siteStats();
  const t = A.meta.total_india;
  if (X.india_rows !== t) throw new Error(`site_stats() India count ${X.india_rows} does not match atlas ${t}. Run buildatlas.js first.`);

  const v = {
    as_of: LONG(A.meta.as_of), as_of_iso: A.meta.as_of, year: A.meta.as_of.slice(0, 4),
    world: fmt(A.meta.total_global), world_floor: floor100(A.meta.total_global),
    india: fmt(t), india_floor: floor100(t),
    countries: fmt(A.meta.countries),
    india_cities: fmt(A.cities.length + A.cities_single),
    multi_city: fmt(A.meta.multi_city), multi_city_pct: pc(A.meta.multi_city, t) + '%',
    gen34_pct: pct0(val('generation', 'India', 'Gen 3') + val('generation', 'India', 'Gen 4'), known('generation', 'India')),
    gen4: fmt(val('generation', 'India', 'Gen 4')),
    gen_known: fmt(known('generation', 'India')),
    under500_pct: pct0(val('size', 'India', '1-100') + val('size', 'India', '101-500'), known('size', 'India')),
    size_5000: fmt(val('size', 'India', '5000+')),
    since2023: fmt(val('vintage', 'India', '2023-2026')),
    pharma_india: fmt(val('industry', 'India', 'Pharma & Life Sciences')),
    setup_recorded: fmt(X.setup_recorded), setup_captive: fmt(X.setup_captive), setup_bot: fmt(X.setup_bot),
    setup_jv: fmt(X.setup_jv), setup_blank: fmt(X.setup_blank), setup_captive_acq: fmt(X.setup_captive_via_acq),
    setup_captive_pct: pct0(X.setup_captive, X.setup_recorded),
    pre2015_gen34_pct: pct0(X.pre2015_gen34, X.pre2015_known_gen)
  };
  const SLUG = { Bengaluru: 'bengaluru', Pune: 'pune', Hyderabad: 'hyderabad', 'Delhi NCR': 'ncr', Mumbai: 'mumbai', Chennai: 'chennai' };
  for (const [scope, s] of Object.entries(SLUG)) {
    const n = A.scope_totals[scope];
    v[s] = fmt(n);
    v[s + '_share'] = pc(n, t) + '%';
    v[s + '_since2023'] = fmt(val('vintage', scope, '2023-2026'));
    v[s + '_since2023_pct'] = pc(val('vintage', scope, '2023-2026'), n) + '%';
    v[s + '_dataai_pct'] = pc(val('domain', scope, 'Data, Analytics & AI'), n) + '%';
    v[s + '_pharma'] = fmt(val('industry', scope, 'Pharma & Life Sciences'));
  }
  for (const c of ['Noida', 'Gurugram', 'Greater Noida', 'Coimbatore', 'Ahmedabad', 'Kolkata']) {
    const r = A.cities.find(x => x[0] === c); if (r) v['city_' + c.toLowerCase().replace(/\s+/g, '_')] = fmt(r[1]);
  }
  // the six-city ranking line used in copy, largest first
  v.top_cities = Object.entries(SLUG).sort((a, b) => A.scope_totals[b[0]] - A.scope_totals[a[0]]).map(([sc]) => `${sc} ${fmt(A.scope_totals[sc])}`).join(', ');

  const out = { _about: 'Generated by _tools/stats.js. Do not edit by hand; run node _tools/refresh.js.', generated: new Date().toISOString(), values: v };
  fs.writeFileSync(S + 'assets/data/site-stats.json', JSON.stringify(out, null, 1) + '\n');
  console.log(`site-stats.json: ${Object.keys(v).length} figures (India ${v.india}, world ${v.world}, as of ${v.as_of})`);
})().catch(e => { console.error('stats.js failed:', e.message); process.exit(1); });
