const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function expertEmail(job,row,p,{from,team}){
 const reference=row.expert_code;let to,subject,paragraphs;
 if(job.event==='registration_applicant'){
  to=p.email;subject='Expert registration received | GCCPROs';paragraphs=[`Thank you, ${p.name}. Your private expert registration has been received.`,`Application reference: ${reference}.`,`Our team will review your professional profile and verify your contact details, identity and experience. We may contact you for clarification. Your identifying details and documents are not included in client profiles.`,`Registration is not network approval or a guarantee of assignments. Selected engagements offer USD 200–500 per hour, with the rate and scope agreed before you accept.`,`To request a correction or withdraw your application, reply to this email and quote your reference. Do not email government ID documents.`];
 }else if(job.event==='registration_team'){
  to=team;subject='New private expert registration | '+reference;paragraphs=[`A new expert application is ready for private review.`,`Application reference: ${reference}.`,`Open the private expert workspace and sign in with your authorised reviewer account: https://www.gccpros.com/expert-admin.html`,`Identity, phone, work history and documents are available only after reviewer authentication. They are intentionally excluded from this email.`];
 }else if(job.event==='approval_applicant'){
  to=p.email;subject='Your GCCPROs expert profile is approved';paragraphs=[`Hello ${p.name}, your GCCPROs expert profile has been approved for matching.`,`Application reference: ${reference}.`,`We can now consider your reviewed capability profile for relevant consulting opportunities. Clients receive an anonymised capability profile; your identifying details and ID documents remain private to GCCPROs.`,`The team will contact you when a suitable requirement arises. Every engagement requires your acceptance of the scope, availability, participation boundaries and agreed honorarium. Approval does not guarantee assignments or approve your requested rate.`,`Reply to this email to update your availability or request a profile correction. Do not email government ID documents.`];
 }else throw new Error('Unsupported email event');
 return {from,to:[to],reply_to:team,subject,text:paragraphs.join('\n\n')+'\n\nGCCPROs · Chartered Times LLP',html:'<div style="font-family:Arial,sans-serif;max-width:620px;color:#122338"><h1 style="font-size:23px">GCCPROs</h1>'+paragraphs.map(p=>'<p style="line-height:1.65">'+escape(p)+'</p>').join('')+'<p style="font-size:12px;color:#536474">GCCPROs · Chartered Times LLP</p></div>'};
}
export async function dispatchEmails({repo,box,sendEmail,from,team}){
 const jobs=await repo.claimMail();let sent=0,failed=0;
 for(const job of jobs){try{const row=await repo.get(job.application_id);if(!row)throw Error('Missing profile');if(job.event==='approval_applicant'&&row.status!=='approved'){await repo.finishMail(job.id,job.lease_id,true,'suppressed-state-change');continue;}const p=JSON.parse(new TextDecoder().decode(await box.open(row.profile_encrypted,'profile:'+row.id)));const message=expertEmail(job,row,p,{from,team});const providerId=await sendEmail(message,'expert-email/'+job.id);if(!providerId)throw Error('No provider receipt');await repo.finishMail(job.id,job.lease_id,true,providerId);sent++;}catch{await repo.finishMail(job.id,job.lease_id,false,null);failed++;}}
 return {claimed:jobs.length,sent,failed};
}
